### ISSUE TITLE
OOM in Re-assembled

### ISSUE THREAD

**Issue by if0s** [elasticio/splitter-component#103]
# Component Bug Report

## Description

OOM in Re-assembled action when you have more than 1000 000 messages

## Component Version

1.5.0

## Steps to Reproduce

1. Create flow win code component that will emit 2000 000 messages
2. Put splitter as second step with re-assamble action

## Actual Result

OOM after 1 000 000 messages

## Expected Result

No OOM

**Comment by MarianaZaloha** [comment]
https://github.com/elasticio/splitter-component/releases/tag/1.5.1
