### ISSUE TITLE
Deploy of updated component

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/splitter-component#15]
There was implemented fix. It replaces async behavior of `forEach` implementation by replacing it to classical `for`.
This fix will bring flow-control feature to the component.
Fix: https://github.com/elasticio/splitter-component/commit/81c0882e544a9d467a23166ee9dff265b3869a66

Deploy on `westeros` is required.

**Comment by stas-fomenko** [comment]
@ElBabbler @kirill-levitskiy component is still failed due to OOM and flow suspended after enVars are applied: 
``` DATA_RATE_LIMIT 10 ```
``` RATE_INTERVAL 1000 ```
