### ISSUE TITLE
Component does not await correctly when emitting data

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/splitter-component#35]
Same bug as https://github.com/elasticio/jsonata-transform-component/issues/28

from: splitter-component/lib/actions/splitOnJsonata.js
```
results.forEach(async (result) => {
        if (result) {
            await this.emit('data', messages.newMessageWithBody(result));
        }
    });
```
This code does not handle asynchronous call emit correctly.
see e.g. here: https://stackoverflow.com/questions/37576685/are-there-any-issues-with-using-async-await-in-a-foreach-loop  It should be replaced with either `for (... of ...) {await ...}` so that:
* Emit statements do not overlap timewise
* Done is not emitted before each message is emitted.
* The next inbound message does not start being processed before the previous message is finished.

**Comment by kirill-levitskiy** [comment]
**DoD**
**Development:**
- [ ] use new logger
- [ ] component should be dockerised, add: "buildType":"docker" line into component.json
- [ ] sailor version is changed from -.-.- to -.-.-
- [ ] CHANGELOG.md is updated
**QA:**
- [ ] Smoke test is finished
- [ ] Regression testing is finished (optional)
- [ ] Support is asked to deploy to the production stage (app.elastic.io) and/or another required stage
- [ ] Component is actually deployed to the production stage (app.elastic.io) and/or another required stage
- [ ] Smoke after deploying to the production stage
