### ISSUE TITLE
Re-assemble: Make Message ID optional 

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/splitter-component#66]
# Other Feature Request

## Description
In the current re-assemble action, we expect [a message ID](https://github.com/elasticio/splitter-component/blob/7eadec570744872b4ad3f2f6ea01e719498d3f80/component.json).  Currently, this property is required. However, in some cases, there is no natural ID to associate with a data record and a random ID must be generated. However, requiring the integrator to generate random numbers could be tedious. Ideally, this property would become optional. If no value is supplied for this property, then the component should generate a random guid for this property.

**Comment by jhorbulyk** [comment]
Implemented in #78

**Comment by A3a3e1** [comment]
Update Sailor 2.6.24 -> 2.6.26
