### ISSUE TITLE
I'm done button after splitter is confusing

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/splitter-component#9]
After splitter component test-stage a screen is presented with two buttons: **+Add another step** and **I'm done**. When **I'm done** is pressed the flow is saved in that stage. This is pretty confusing since splitter should not be the last component in the flow. The screenshot is here: [http://take.ms/qvkUg](http://take.ms/qvkUg)

To reproduce:

1. Select WebHook and use an array in the input field:
```json
{ "patients" : [
	{"patient1" : "value1"},
	{"patient2" : "value2"} 
	] 
}
```
2. Add Splitter component and select the `patients` property to be used for splitting and press continue.
3. Test the step. After sucsessful test you will be presented with the screen shown on the screenshot.

**Comment by kirill-levitskiy** [comment]
The issue has been solved in the new UI (mapper):
![image](https://user-images.githubusercontent.com/40201204/73831579-3fc7f600-480f-11ea-9b06-127633cf5218.png)
